name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [interno, externo]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Clasp
      run: npm install -g @google/clasp

    - name: Create clasprc.json
      env:
        CLASPRC_CONTENT: ${{ secrets[format('CLASPRC_{0}', matrix.target)] }}
      run: printf '%s' "$CLASPRC_CONTENT" > ~/.clasprc.json

    - name: Select Clasp project
      run: cp ".clasp.${{ matrix.target }}.json.example" .clasp.json

    - name: Push code to Apps Script (${{ matrix.target }})
      run: clasp push -f
